
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.mailgun.org
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
spring.jpa:
  generate-ddl: true
SECRET_KEY: "supersecretkeysupersecretkeysupersecretkeysupersecretkeysupersecretkeysupersecretkeysupersecretkeysupersecretkeysupersecretkeysupersecretkeysupersecretkeysupersecretkey"
CLIENT_URL: "http://localhost:3000"
logging:
  level:
    org:
      springframework:
        security: DEBUG